#cloud-config
package_update: true
packages:
  - apache2
  - php
  - adminer

runcmd:
  - sudo a2enconf adminer
  - sudo systemctl restart apache2

write_files:
  - path: /var/www/html/index.html
    content: |
      <html>
        <body>
          <h1>Willkommen auf der Startseite</h1>
        </body>
      </html>
  - path: /var/www/html/info.php
    content: |
      <?php phpinfo(); ?>
  - path: /var/www/html/db.php
    content: |
      <?php
        $conn = new mysqli('3.90.99.233', 'admin', 'admin', 'KN05');
        if ($conn->connect_error) {
          die("Connection failed: " . $conn->connect_error);
        }
        echo "Connected successfully to the database.";
      ?>
